"""empty message

Revision ID: 76f56774c7c0
Revises: 91ba5e4ce23e
Create Date: 2022-06-06 14:38:15.762593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f56774c7c0'
down_revision = '91ba5e4ce23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'name')
    # ### end Alembic commands ###
